### ISSUE TITLE
Here-Strings are breaking the highlighting

### ISSUE THREAD

**Issue by EinPinsel** [SublimeText/PowerShell#130] opened 2015-05-28 11:39 UTC
If you're using a Here-String, the formatting after "@ is broken. 
![2015-05-28 13_38_42](https://cloud.githubusercontent.com/assets/12642546/7859199/f84bef6a-053e-11e5-81d7-c21e06ddc9f4.png)

**Comment by vors** [comment] 2015-05-29 16:43
It's by design: here-string cannot have indentation for the closing `"@`:

PowerShell_ISE:
![image](https://cloud.githubusercontent.com/assets/816680/7887571/01002510-05e7-11e5-83cf-86a4e7aa6572.png)

**Closed by vors** 2015-05-29 16:43 UTC
